language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer dumpautoload -o
